// Master Departments
export const MASTER_DEPARTMENTS = [
  "HR",
  "IT",
  "Finance",
  "Marketing",
  "Sales",
  "Operations",
  "Engineering",
];

// Master Roles
export const MASTER_ROLES = [
  "HR Manager",
  "Senior Developer",
  "Financial Analyst",
  "Marketing Director",
  "Account Executive",
  "DevOps Engineer",
  "Talent Acquisition",
  "Senior Analyst",
  "Operations Manager",
  "Systems Administrator",
  "Support Lead",
  "Product Owner",
];

// Sample employees (used if storage empty)
export const SAMPLE_EMPLOYEES = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@example.com",
    department: "HR",
    role: "HR Manager",
  },
  {
    id: 2,
    firstName: "Bob",
    lastName: "Johnson",
    email: "b.johnson@example.com",
    department: "Engineering",
    role: "Senior Developer",
  },
  {
    id: 3,
    firstName: "Charlie",
    lastName: "Lee",
    email: "charlie.lee@example.com",
    department: "Finance",
    role: "Financial Analyst",
  },
  {
    id: 4,
    firstName: "Diana",
    lastName: "Brown",
    email: "diana.b@example.com",
    department: "Marketing",
    role: "Marketing Director",
  },
  {
    id: 5,
    firstName: "Eve",
    lastName: "Davis",
    email: "e.davis@example.com",
    department: "Sales",
    role: "Account Executive",
  },
  {
    id: 6,
    firstName: "Frank",
    lastName: "Wilson",
    email: "frank.w@example.com",
    department: "Engineering",
    role: "DevOps Engineer",
  },
  {
    id: 7,
    firstName: "Grace",
    lastName: "Martinez",
    email: "g.martinez@example.com",
    department: "HR",
    role: "Talent Acquisition",
  },
  {
    id: 8,
    firstName: "Henry",
    lastName: "Garcia",
    email: "henry.g@example.com",
    department: "Finance",
    role: "Senior Analyst",
  },
  {
    id: 9,
    firstName: "Ivy",
    lastName: "Chen",
    email: "ivy.chen@example.com",
    department: "Operations",
    role: "Operations Manager",
  },
  {
    id: 10,
    firstName: "Jack",
    lastName: "Williams",
    email: "jack.w@example.com",
    department: "IT",
    role: "Systems Administrator",
  },
  {
    id: 11,
    firstName: "Karen",
    lastName: "Taylor",
    email: "karen.t@example.com",
    department: "Customer Support",
    role: "Support Lead",
  },
  {
    id: 12,
    firstName: "Liam",
    lastName: "Nguyen",
    email: "liam.n@example.com",
    department: "Product",
    role: "Product Owner",
  },
];
